language: java

addons:
  hosts:
    - javaclient.jsreport

services:
  - docker

before_install:
  - docker pull jsreport/jsreport:2.9.0
  - docker run -v "./src/test/server/jsreport:/app" -p 9080:5488 --hostname javaclient.jsreport jsreport/jsreport:2.9.0
