language: java

addons:
  hosts:
    - jsreport

services:
  - docker

before_install:
  - docker pull jsreport/jsreport:2.9.0
  - docker run -d -p 9080:5488 --hostname jsreport jsreport/jsreport:2.9.0

script:
  - mvn test -B -P allTests

